Add support for the CellCam Kikker camera.
outofculture/acq4 pull request #15
Opened 2022-11-06 20:07 UTC by marsiwiec

Hi,

I added support for the CellCam Kikker camera. The trick was to add a getExposure() call because the MicroManager driver does not expose this as a property. The other changes are just downstream from that. Everything seems to be working on my end. Hope this helps!

Marcin

2022-11-09 21:03 UTC, outofculture requested changes
These mostly all seem alright, but I'd like to reduce the chance of this code altering the behavior of other cameras. To that end, I would just add `and self.camName == "CellCam"` to all the if statements regarding `"Exposure"`. Let me know if you want to do that, or I can just take this over, no problem.

2022-11-09 21:03 UTC, outofculture commented on acq4/devices/MicroManagerCamera/mmcamera.py
> +                val = self.mmc.getProperty(self.camName, str(paramTrans))
This line probably needs to be in an else block?

2022-11-09 21:03 UTC, outofculture commented on acq4/devices/MicroManagerCamera/mmcamera.py
> +                        if self.mmc.hasPropertyLimits(self.camName, prop):
This branch of logic is still valid for non-CellCam cameras.

2022-11-09 21:03 UTC, outofculture commented on acq4/devices/MicroManagerCamera/mmcamera.py
> +                        vals = (1, 100) # sensible range of exposure values...
😢  I wish we didn't have to guess. This is a fine guess, though.

2022-11-09 21:03 UTC, outofculture commented on acq4/devices/MicroManagerCamera/mmcamera.py
> +                    readonly = self.mmc.isPropertyReadOnly(self.camName, prop)
This is still valid code for non-CellCam cameras.

2022-11-09 21:03 UTC, outofculture commented on acq4/devices/MicroManagerCamera/mmcamera.py
> +                    readonly = self.mmc.isPropertyReadOnly(self.camName, prop)
Oh, also, `readonly` is used in code further along, so we would need a default value (I'm guessing `False`) for CellCam.

2022-11-10 17:06 UTC, marsiwiec commented on acq4/devices/MicroManagerCamera/mmcamera.py
> +                    readonly = self.mmc.isPropertyReadOnly(self.camName, prop)
```suggestion
                    readonly = self.mmc.isPropertyReadOnly(self.camName, prop)
                else:
                    readonly = False
```

2022-11-10 17:13 UTC, marsiwiec reviewed
Hi @outofculture, I made the suggested changes, let me know if this is ok.

2022-11-10 17:13 UTC, marsiwiec commented on acq4/devices/MicroManagerCamera/mmcamera.py
> +                    readonly = self.mmc.isPropertyReadOnly(self.camName, prop)
Yeah, so we could perhaps add an else block.
```suggestion
                    readonly = self.mmc.isPropertyReadOnly(self.camName, prop)
                else:
                    readonly = False
```

2022-11-10 17:13 UTC, marsiwiec commented on acq4/devices/MicroManagerCamera/mmcamera.py
> +                        vals = (1, 100) # sensible range of exposure values...
Yeah, it sucks with the guesses. If only they would add exposure to properties...

2022-11-10 17:13 UTC, marsiwiec commented on acq4/devices/MicroManagerCamera/mmcamera.py
> +                        if self.mmc.hasPropertyLimits(self.camName, prop):
ok!

2022-11-10 17:13 UTC, marsiwiec commented on acq4/devices/MicroManagerCamera/mmcamera.py
> +                val = self.mmc.getProperty(self.camName, str(paramTrans))
You're right, my bad!
```suggestion
            else:
                val = self.mmc.getProperty(self.camName, str(paramTrans))
```

2022-11-10 17:20 UTC, marsiwiec commented on acq4/devices/MicroManagerCamera/mmcamera.py
> +                if param == 'Exposure': # workaround for CellCam - call to setExposure(), not getProperty()
```suggestion
                if param == 'Exposure' and self.camName == "CellCam": # workaround for CellCam - call to setExposure(), not getProperty()
```

2022-11-10 17:20 UTC, marsiwiec commented on acq4/devices/MicroManagerCamera/mmcamera.py
> +            if paramTrans == 'Exposure':
```suggestion
            if paramTrans == 'Exposure' and self.camName == "CellCam":
```

2022-11-11 00:46 UTC, merged